/*
	This file is automatically adjusted by CMake

	Its purpose is to configure each liblightmodbus header file,
	so the user does not have to pass tons of compiler options each time
	he/she wants to compile the library.
	It also serves as a pretty nice source of information about current
	library setup.

	Do not edit this file manually unless you know what you are doing.
*/
#ifndef LIGHTMODBUS_LIBCONF_H
#define LIGHTMODBUS_LIBCONF_H

#define LIGHTMODBUS_VERSION "2.0"
#define LIGHTMODBUS_GIT_VERSION "v2.0-2-21-g9a2471"
#define LIGHTMODBUS_SLAVE_BASE
//#define LIGHTMODBUS_F01S
//#define LIGHTMODBUS_F02S
#define LIGHTMODBUS_F03S
//#define LIGHTMODBUS_F04S
//#define LIGHTMODBUS_F05S
//#define LIGHTMODBUS_F06S
//#define LIGHTMODBUS_F15S
//#define LIGHTMODBUS_F16S
//#define LIGHTMODBUS_F22S
#define LIGHTMODBUS_SLAVE_USER_FUNCTIONS
#define LIGHTMODBUS_REGISTER_CALLBACK
#define LIGHTMODBUS_EXPERIMENTAL
// (6 + (4 * 4)) + 1
#define LIGHTMODBUS_STATIC_MEM_SLAVE_RESPONSE 23
#define LIGHTMODBUS_STATIC_MEM_SLAVE_REQUEST 9

#define LIGHTMODBUS_MASTER_BASE
#define LIGHTMODBUS_F01M
//#define LIGHTMODBUS_F02M
//#define LIGHTMODBUS_F03M
//#define LIGHTMODBUS_F04M
#define LIGHTMODBUS_F05M
//#define LIGHTMODBUS_F06M
//#define LIGHTMODBUS_F15M
//#define LIGHTMODBUS_F16M
//#define LIGHTMODBUS_F22M
//#define LIGHTMODBUS_MASTER_USER_FUNCTIONS
//#define LIGHTMODBUS_COIL_CALLBACK
//#define LIGHTMODBUS_MASTER_INVASIVE_PARSING
#define LIGHTMODBUS_STATIC_MEM_MASTER_DATA 3
#define LIGHTMODBUS_STATIC_MEM_MASTER_REQUEST 9
#define LIGHTMODBUS_STATIC_MEM_MASTER_RESPONSE 9

#define LIGHTMODBUS_LITTLE_ENDIAN

#endif
